### PR TITLE
performance improvements

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Supersedes #302

**Comment by scottmarlow** [comment]
Am I still the only one getting test failures (previously got them with https://github.com/smallrye/jandex/pull/302 also):

> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/smarlow/.m2/repository/org/codehaus/groovy/groovy-all/2.4.21/groovy-all-2.4.21.jar) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/defaultFileset/target/dependency/jandex.idx does not exist. Expression: jandexFile.exists()
> [INFO]           defaultFileset/pom.xml ........................... FAILED (2.7 s)
> [INFO] Building: multipleIndices/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/multipleIndices/target/classes/META-INF/jandex.idx does not exist. Expression: jandexFile.exists()
> [INFO]           multipleIndices/pom.xml .......................... FAILED (1.9 s)
> [INFO] Building: filesets/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/filesets/target/classes/META-INF/jandex.idx does not exist. Expression: jandexFile.exists()
> [INFO]           filesets/pom.xml ................................. FAILED (1.9 s)
> [INFO] Building: dependencies/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/dependencies/target/classes/META-INF/jandex.idx does not exist. Expression: jandexFile.exists()
> [INFO]           dependencies/pom.xml ............................. FAILED (2.9 s)
> [INFO] Building: reproducible/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File does not exist: /home/smarlow/work/jandex/maven-plugin/target/it/reproducible/target/classes/META-INF/jandex.idx. Expression: jandexFile.exists()
> [INFO]           reproducible/pom.xml ............................. FAILED (2.1 s)
> [INFO] Building: jar/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/jar/target/jandex-maven-plugin-jar-1.0-SNAPSHOT.jar does not exist. Expression: jarFile.exists()
> [INFO]           jar/pom.xml ...................................... FAILED (2.4 s)
> [INFO] Building: smoketest/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/smoketest/target/classes/META-INF/jandex.idx does not exist. Expression: jandexFile.exists()
> [INFO]           smoketest/pom.xml ................................ FAILED (1.9 s)
> [INFO] Building: noFileset/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]   java.lang.AssertionError: File /home/smarlow/work/jandex/maven-plugin/target/it/noFileset/target/classes/META-INF/jandex.idx does not exist. Expression: jandexFile.exists()
> [INFO]           noFileset/pom.xml ................................ FAILED (1.9 s)
> [INFO] Building: someLibraries/pom.xml
> [INFO] run post-build script verify.groovy
> [INFO]           someLibraries/pom.xml ............................ SUCCESS (6.1 s)
> [INFO] -------------------------------------------------
> [INFO] Build Summary:
> [INFO]   Passed: 1, Failed: 8, Errors: 0, Skipped: 0
> [INFO] -------------------------------------------------
> [ERROR] The following builds failed:
> [ERROR] *  defaultFileset/pom.xml
> [ERROR] *  multipleIndices/pom.xml
> [ERROR] *  filesets/pom.xml
> [ERROR] *  dependencies/pom.xml
> [ERROR] *  reproducible/pom.xml
> [ERROR] *  jar/pom.xml
> [ERROR] *  smoketest/pom.xml
> [ERROR] *  noFileset/pom.xml

**Comment by Ladicek** [comment]
I didn't try with Maven 3.9.0 yet, but I have never seen these tests fail (except when I did something wrong, of course :-) ).

**Comment by scottmarlow** [comment]
Thanks for the reminder, it works great with Maven 3.8.x

**Review by franz1981 — APPROVED** [review]
LGTM!

**Pull request merged**
